base: &base
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432

development: &development
  <<: *base
  database: double_entry_bookkepping
  username: orbanbotond
  password: 

test: &test
  <<: *base
  database: double_entry_bookkepping_test
  username: orbanbotond
  password: 
